package com.unfurl.dcp.broker;

public enum DispositionReason {
    MATCH_FOUND,
    NO_MATCHING_CONTRACT,
    SIGNATURE_INVALID,
    CLAIM_MALFORMED,
    DCP_VERSION_UNSUPPORTED,
    BROKER_ACCEPT_INVALID,
    CONTRACT_NOT_FOUND,
    CONTRACT_INVALIDATED
}
