package com.unfurl.dcp.validation;

public enum ErrorCode {
    VALIDATION_FAILED,
    CLAIM_MALFORMED,
    MANIFEST_MISMATCH,
    CONTRACT_PARTIES_INVALID,
    CONTRACT_PROVENANCE_INCONSISTENT,
    CONTRACT_TRUST_INCONSISTENT,
    SIGNATURE_INVALID,
    BINDING_INLINE_SECRET,
    BINDING_OVERRIDES_OWNERSHIP,
    RESOLUTION_FAILED,
    MULTIPLE_MATCHES,
    OFFER_VERSION_UNSATISFIED,
    ACCESS_DENIED,
    NO_MATCHING_CONTRACT,
    DCP_VERSION_UNSUPPORTED,
    BROKER_ACCEPT_INVALID,
    CONTRACT_NOT_FOUND,
    CONTRACT_INVALIDATED
}
